#
# Configuration file for classification model example
#

#
# Problem type
#
#  Valid values: 'classification' or 'regression'
PROBLEM_TYPE: 'classification'

#
# base directory for model building
#
ROOT_DIR: '.'

#
# Directory Structures
#

# location of model files
MODEL_DIR: 'models'

# directory for data feature sets
DATA_DIR: 'data'

# location of model results tracker file
RESULTS_DIR: 'results'

# location for python scripts to create feature sets
MUNGE_DIR: 'munge'


#
# variablses that serve as identifiers
#
ID_VAR: ['ID']

#
# response variable
#
TARGET_VAR: 'target'


#
# Kaggle Submission Heaaders
#
KAGGLE_SUBMISSION_HEADERS: ['ID','PredictedProb']

#
# Method for generating test data set predictions
#  Valid values:
#     all_data_model
#     k-fold_average_model
#
TEST_PREDICTION_METHOD: k-fold_average_model

