#
# Configuration file for classification model example
#

#
# Problem type
#
#  Valid values: 'classification' or 'regression'
PROBLEM_TYPE: 'regression'

#
# base directory for model building
#
ROOT_DIR: '.'

#
# Directory Structures
#

# location of model files
MODEL_DIR: 'reg_models'

# directory for data feature sets
DATA_DIR: 'reg_data'

# location of model results tracker file
RESULTS_DIR: 'reg_results'

# location for python scripts to create feature sets
MUNGE_DIR: 'reg_munge'


#
# user supplied Kaggle contest specific functions:
#   calculateKaggleMetric
#   formatKaggleSubmission
#
KAGGLE_CONTEST_FUNCTIONS:  'reg_kaggle_user_functions.py'


#
# variablses that serve as identifiers
#
ID_VAR: ['Id']

#
# response variable
#
TARGET_VAR: 'SalePrice'


#
# Kaggle Submission Heaaders
#
KAGGLE_SUBMISSION_HEADERS: ['Id','SalePrice']

#
# Method for generating test data set predictions
#  Valid values:
#     all_data_model
#     k-fold_average_model
#
TEST_PREDICTION_METHOD: k-fold_average_model

